import { useState, type ReactNode } from "react";
import { useNavigate } from "react-router";
import { DashboardLayout } from "../../components/DashboardLayout";
import { GlassCard } from "../../components/GlassCard";
import { Button } from "../../components/ui/button";
import { Input } from "../../components/ui/input";
import { Badge } from "../../components/ui/badge";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "../../components/ui/tabs";
import { Avatar, AvatarFallback } from "../../components/ui/avatar";
import { Switch } from "../../components/ui/switch";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "../../components/ui/select";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter } from "../../components/ui/dialog";
import { BarChart, Bar, LineChart, Line, PieChart, Pie, Cell, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer } from "recharts";
import { Activity, AlertTriangle, BarChart3, Bell, Briefcase, Building, Calendar, CheckCircle2, Database, Download, Edit3, Eye, FileText, Filter, Lock, Monitor, Plus, RefreshCcw, Search, Server, Settings, Shield, Sparkles, Trash2, UserCog, Users, XCircle } from "lucide-react";

const gold = "#D4AF37";
const users = [
  ["Kavishi Rajasekara", "kavishi@email.com", "Job Seeker", "Active", "TalentAI", "18/06/2026"],
  ["Sarah Jenkins", "sarah@acme.com", "Recruiter", "Active", "Acme Corp", "11/06/2026"],
  ["David Kim", "david@acme.com", "Hiring Manager", "Suspended", "Acme Corp", "05/06/2026"],
  ["Elena Rodriguez", "elena@talentai.com", "Administrator", "Active", "TalentAI", "01/06/2026"],
];
const orgs = [["Acme Corp", "Software", "128", "Enterprise", "Active"], ["Virtusa", "Technology Services", "86", "Growth", "Active"], ["LankaFin", "Finance", "42", "Starter", "Suspended"]];
const jobs = [["Software Engineer Intern", "Acme Corp", "Active", "18/06/2026", "420"], ["QA Intern", "Virtusa", "Closed", "12/06/2026", "118"], ["Backend Developer", "LankaFin", "Active", "09/06/2026", "84"]];
const apps = [["Kavishi Rajasekara", "Software Engineer Intern", "Acme Corp", "Under Review", "18/06/2026"], ["Nimal Perera", "QA Intern", "Virtusa", "Shortlisted", "17/06/2026"]];
const chart = [{ name: "Users", value: 12480 }, { name: "Jobs", value: 642 }, { name: "Apps", value: 18420 }, { name: "Interviews", value: 1284 }, { name: "Hires", value: 326 }];

function Header({ title, subtitle }: { title: string; subtitle: string }) { return <div className="mb-6"><p className="text-sm text-[#D4AF37]">Administrator / {title}</p><h1 className="mt-2 text-3xl font-semibold text-white">{title}</h1><p className="text-gray-400 max-w-4xl">{subtitle}</p></div>; }
function AdminCard({ title, value, icon: Icon, to }: { title: string; value: string; icon: typeof Users; to: string }) { const navigate = useNavigate(); return <button onClick={() => navigate(to)} className="text-left rounded-lg border border-[#D4AF37]/20 bg-[#1E1E1E]/60 backdrop-blur-md p-5 hover:border-[#D4AF37]/50 hover:bg-[#2D2D2D]/60 transition-all"><div className="flex justify-between gap-3"><div><p className="text-xs uppercase tracking-[0.18em] text-gray-500">{title}</p><h3 className="mt-2 text-2xl font-semibold text-white">{value}</h3></div><div className="rounded-xl bg-[#D4AF37]/10 p-3 h-fit"><Icon className="h-5 w-5 text-[#D4AF37]" /></div></div></button>; }
function Toolbar({ children }: { children: ReactNode }) { return <GlassCard className="p-4 mb-5"><div className="flex flex-wrap gap-3">{children}</div></GlassCard>; }
function Table({ heads, rows, actions }: { heads: string[]; rows: string[][]; actions: (row: string[]) => ReactNode }) { return <GlassCard className="overflow-hidden"><div className="overflow-x-auto"><table className="w-full min-w-[860px] text-sm"><thead><tr>{heads.map(h => <th key={h} className="px-5 py-4 text-left text-xs uppercase tracking-[.18em] text-gray-500 border-b border-[#D4AF37]/10">{h}</th>)}<th className="px-5 py-4 text-left text-xs uppercase tracking-[.18em] text-gray-500 border-b border-[#D4AF37]/10">Actions</th></tr></thead><tbody>{rows.map((r,i)=><tr key={i} className="hover:bg-[#D4AF37]/5">{r.map((c,j)=><td key={j} className="px-5 py-4 border-b border-[#D4AF37]/10 text-gray-300">{j===0?<b className="text-white">{c}</b>: c}</td>)}<td className="px-5 py-4 border-b border-[#D4AF37]/10">{actions(r)}</td></tr>)}</tbody></table></div></GlassCard>; }
const Action = ({ children, to, variant="outline" }: { children: ReactNode; to: string; variant?: "outline" | "default" | "destructive" | "ghost" }) => { const n=useNavigate(); return <Button size="sm" variant={variant} onClick={() => n(to)}>{children}</Button>; };

export function AdminDashboard() { return <DashboardLayout role="admin"><Header title="Platform Dashboard" subtitle="Complete overview of TalentAI performance, user activity, organizations, jobs, applications, interviews, AI usage, and infrastructure health." /><div className="grid sm:grid-cols-2 xl:grid-cols-4 gap-4 mb-6">{[
["Total Users","12,480",Users,"/admin/users"],["Total Recruiters","842",UserCog,"/admin/users?role=recruiter"],["Total Hiring Managers","516",Users,"/admin/users?role=hiring-manager"],["Total Job Seekers","11,122",Users,"/admin/users?role=jobseeker"],["Total Organizations","326",Building,"/admin/organizations"],["Total Jobs Posted","642",Briefcase,"/admin/jobs"],["Active Jobs","488",CheckCircle2,"/admin/jobs/active"],["Closed Jobs","154",XCircle,"/admin/jobs/closed"],["Applications Received","18,420",FileText,"/admin/applications"],["Interviews Scheduled","1,284",Calendar,"/admin/interviews"],["Hires Completed","326",Shield,"/admin/reports/hiring"],["AI Resume Screenings","9,822",Sparkles,"/admin/ai-monitoring"],["AI Candidate Rankings","4,211",Sparkles,"/admin/ai-monitoring"],["AI Recommendations Generated","16,480",Sparkles,"/admin/ai-monitoring"],["AI Accuracy Score","94.2%",BarChart3,"/admin/ai-analytics"],["System Health","99.98%",Activity,"/admin/monitoring"],["Server Status","Operational",Server,"/admin/infrastructure"],["Database Status","Healthy",Database,"/admin/database"],["API Response Time","142ms",Monitor,"/admin/api-analytics"]].map(([t,v,I,to])=><AdminCard key={t as string} title={t as string} value={v as string} icon={I as typeof Users} to={to as string}/>)}</div><div className="grid xl:grid-cols-3 gap-6"><GlassCard className="xl:col-span-2 p-6"><h2 className="text-xl text-white font-semibold mb-4">Platform Statistics</h2><ResponsiveContainer width="100%" height={300}><BarChart data={chart}><CartesianGrid strokeDasharray="3 3" stroke="#2D2D2D"/><XAxis dataKey="name" stroke="#999"/><YAxis stroke="#999"/><Tooltip contentStyle={{backgroundColor:"#1E1E1E",border:"1px solid rgba(212,175,55,.25)",color:"#fff"}}/><Bar dataKey="value" fill={gold} radius={[8,8,0,0]} onClick={() => location.assign('/admin/analytics/detail')}/></BarChart></ResponsiveContainer></GlassCard><NotificationsMini /></div></DashboardLayout>; }
function NotificationsMini(){const n=useNavigate();return <GlassCard className="p-6"><h2 className="text-xl text-white font-semibold mb-4">Recent Notifications</h2>{[["User Registered","/admin/users/profile"],["Organization Created","/admin/organizations/profile"],["Job Posted","/admin/jobs/details"],["AI Alert","/admin/ai-monitoring"]].map(([x,to])=><button key={x} onClick={()=>n(to)} className="block w-full text-left p-3 rounded-xl bg-[#2D2D2D]/50 border border-[#D4AF37]/10 mb-3 text-gray-300 hover:border-[#D4AF37]/40">🔔 {x}</button>)}</GlassCard>}

export function UserManagement(){return <DashboardLayout role="admin"><Header title="User Management" subtitle="Create Admin, Recruiter, and Hiring Manager employee accounts, edit employee information, assign roles, and activate or deactivate access."/><Toolbar><Input placeholder="Search User" className="max-w-xs bg-[#2D2D2D] border-[#D4AF37]/20 text-white"/><Button variant="outline"><Filter className="mr-2 h-4 w-4"/>Filter Role</Button><Action to="/admin/users/create" variant="default"><Plus className="mr-2 h-4 w-4"/>Create Employee</Action></Toolbar><Table heads={["User Name","Email","Role","Status","Organization","Registration Date"]} rows={users} actions={()=><div className="flex flex-wrap gap-2"><Action to="/admin/users/profile"><Eye className="h-4 w-4"/></Action><Action to="/admin/users/edit"><Edit3 className="h-4 w-4"/></Action><Button size="sm" variant="outline">Activate</Button><Button size="sm" variant="outline">Deactivate</Button><Button size="sm" variant="outline">Reset Password</Button><Button size="sm" variant="destructive"><Trash2 className="h-4 w-4"/></Button></div>}/></DashboardLayout>}
export function UserProfile(){return <Detail title="User Profile" items={["Profile Information","Organization","Role","Activity History","Login History"]}/>}
export function UserForm(){return <DashboardLayout role="admin"><Header title="Employee Account" subtitle="Only administrators can create employee accounts, assign employee roles, edit details, and activate or deactivate access."/><GlassCard className="p-6"><div className="grid md:grid-cols-2 gap-4"><Input placeholder="Full Name" className="bg-[#2D2D2D] border-[#D4AF37]/20 text-white"/><Input placeholder="Email" className="bg-[#2D2D2D] border-[#D4AF37]/20 text-white"/><Select><SelectTrigger className="bg-[#2D2D2D] border-[#D4AF37]/20 text-white"><SelectValue placeholder="Employee Role"/></SelectTrigger><SelectContent><SelectItem value="admin">Admin</SelectItem><SelectItem value="recruiter">Recruiter</SelectItem><SelectItem value="hiring-manager">Hiring Manager</SelectItem></SelectContent></Select><Select><SelectTrigger className="bg-[#2D2D2D] border-[#D4AF37]/20 text-white"><SelectValue placeholder="Account Status"/></SelectTrigger><SelectContent><SelectItem value="active">Active</SelectItem><SelectItem value="inactive">Inactive</SelectItem></SelectContent></Select><Input placeholder="Organization" className="bg-[#2D2D2D] border-[#D4AF37]/20 text-white"/><Input placeholder="Phone Number" className="bg-[#2D2D2D] border-[#D4AF37]/20 text-white"/></div><div className="mt-5 flex flex-wrap gap-3"><Button>Save Employee</Button><Button variant="outline">Activate Account</Button><Button variant="outline">Deactivate Account</Button><Button variant="outline">Cancel</Button></div></GlassCard></DashboardLayout>}

export function RoleManagement(){const rows=[["Administrator","Full platform control","4"],["Recruiter","Company hiring workflows","842"],["Hiring Manager","Candidate evaluation and decisions","516"],["Job Seeker","Candidate job search experience","11,122"]];return <DashboardLayout role="admin"><Header title="Role Management" subtitle="Manage platform RBAC roles, details, and permissions."/><Toolbar><Action to="/admin/roles/create" variant="default"><Plus className="mr-2 h-4 w-4"/>Create Role</Action></Toolbar><Table heads={["Role Name","Description","User Count"]} rows={rows} actions={()=><div className="flex flex-wrap gap-2"><Action to="/admin/roles/details">View Role</Action><Action to="/admin/roles/edit">Edit Role</Action><Action to="/admin/roles/permissions">Manage Permissions</Action><Button size="sm" variant="destructive">Delete Role</Button></div>}/></DashboardLayout>}
export function PermissionsPage(){return <DashboardLayout role="admin"><Header title="Permissions" subtitle="Module-level read, create, update, and delete access configuration."/><Table heads={["Module Name","Read Access","Create Access","Update Access","Delete Access"]} rows={[["Users","Enabled","Enabled","Enabled","Enabled"],["Jobs","Enabled","Enabled","Enabled","Enabled"],["AI Monitoring","Enabled","Disabled","Enabled","Disabled"],["Audit Logs","Enabled","Disabled","Disabled","Disabled"]]} actions={()=><Button size="sm">Save</Button>}/></DashboardLayout>}

export function OrganizationManagement(){return <DashboardLayout role="admin"><Header title="Organization Management" subtitle="Manage organizations, subscriptions, recruiters, hiring managers, and job statistics."/><Toolbar><Action to="/admin/organizations/create" variant="default"><Plus className="mr-2 h-4 w-4"/>Create Organization</Action><Input placeholder="Search organization" className="max-w-xs bg-[#2D2D2D] border-[#D4AF37]/20 text-white"/></Toolbar><Table heads={["Company Name","Industry","Active Users","Subscription Plan","Status"]} rows={orgs} actions={()=><div className="flex flex-wrap gap-2"><Action to="/admin/organizations/profile">View</Action><Action to="/admin/organizations/edit">Edit</Action><Button size="sm" variant="outline">Suspend</Button><Action to="/admin/organizations/upgrade">Upgrade Plan</Action></div>}/></DashboardLayout>}
export function OrganizationProfile(){return <Detail title="Organization Profile" items={["Company Details","Users","Recruiters","Hiring Managers","Job Statistics"]}/>}

export function JobManagement(){return <DashboardLayout role="admin"><Header title="Job Management" subtitle="Inspect platform jobs, details, applications, and hiring status."/><Toolbar><Action to="/admin/jobs/create" variant="default"><Plus className="mr-2 h-4 w-4"/>Create Job</Action><Input placeholder="Search jobs" className="max-w-xs bg-[#2D2D2D] border-[#D4AF37]/20 text-white"/></Toolbar><Table heads={["Job Title","Company","Status","Posted Date","Application Count"]} rows={jobs} actions={()=><div className="flex flex-wrap gap-2"><Action to="/admin/jobs/details">View Job</Action><Action to="/admin/jobs/edit">Edit Job</Action><Button size="sm" variant="outline">Close Job</Button><Button size="sm" variant="outline">Reopen Job</Button><Button size="sm" variant="destructive">Delete Job</Button></div>}/></DashboardLayout>}
export function JobDetails(){return <Detail title="Job Details" items={["Job Description","Requirements","Applications","Hiring Status"]}/>}

export function ApplicationManagement(){return <DashboardLayout role="admin"><Header title="Application Management" subtitle="Review candidate applications, approve stages, reject, and export PDFs."/><Table heads={["Candidate Name","Job Title","Organization","Application Status","Applied Date"]} rows={apps} actions={()=><div className="flex flex-wrap gap-2"><Action to="/admin/applications/details">View Application</Action><Button size="sm">Approve Application</Button><Button size="sm" variant="destructive">Reject Application</Button><Button size="sm" variant="outline"><Download className="h-4 w-4"/></Button></div>}/></DashboardLayout>}
export function ApplicationDetails(){return <Detail title="Application Details" items={["Candidate Information","Resume","Status History","Interview Information"]}/>}

export function InterviewManagement(){return <DashboardLayout role="admin"><Header title="Interview Management" subtitle="Manage interview records, rescheduling, cancellations, meeting rooms, and feedback."/><Table heads={["Candidate Name","Position","Company","Interview Date","Interview Status"]} rows={[["Kavishi Rajasekara","Software Engineer Intern","Acme Corp","24/06/2026","Scheduled"],["Nimal Perera","QA Intern","Virtusa","25/06/2026","Pending"]]} actions={()=><div className="flex flex-wrap gap-2"><Action to="/admin/interviews/details">View Interview</Action><Action to="/admin/interviews/reschedule">Reschedule</Action><Button size="sm" variant="destructive">Cancel</Button><Action to="/interviews/video-room">Join Meeting</Action></div>}/></DashboardLayout>}
export function InterviewDetails(){return <Detail title="Interview Details" items={["Candidate","Recruiter","Hiring Manager","Meeting Link","Feedback"]}/>}

export function AIMonitoring(){return <DashboardLayout role="admin"><Header title="AI Monitoring" subtitle="Monitor resume screenings, rankings, AI usage, errors, recommendations, logs, and insights."/><div className="grid md:grid-cols-2 xl:grid-cols-5 gap-4 mb-6">{["Resume Screening Activity","Candidate Ranking Activity","AI Usage Statistics","AI Errors","AI Recommendations"].map((x,i)=><AdminCard key={x} title={x} value={["9,822","4,211","28k","12","16,480"][i]} icon={Sparkles} to={i===3?"/admin/ai-errors/details":"/admin/ai-logs"}/>)}</div><div className="flex flex-wrap gap-3"><Action to="/admin/ai-logs" variant="default">View Logs</Action><Button><Download className="mr-2 h-4 w-4"/>Export Reports</Button><Action to="/admin/ai-analytics">View AI Insights</Action></div></DashboardLayout>}
export function AnalyticsPage(){return <DashboardLayout role="admin"><Header title="Analytics Dashboard" subtitle="User growth, jobs, applications, interviews, and hiring statistics."/><Toolbar><Action to="/admin/reports/detail" variant="default">View Detailed Report</Action><Button variant="outline">Export PDF</Button><Button variant="outline">Export Excel</Button></Toolbar><div className="grid xl:grid-cols-2 gap-6"><ChartCard title="User Growth"/><ChartCard title="Hiring Statistics"/></div></DashboardLayout>}
function ChartCard({title}:{title:string}){return <GlassCard className="p-6 cursor-pointer" onClick={()=>location.assign('/admin/analytics/detail')}><h2 className="text-xl text-white font-semibold mb-4">{title}</h2><ResponsiveContainer width="100%" height={260}><LineChart data={chart}><XAxis dataKey="name" stroke="#999"/><YAxis stroke="#999"/><Tooltip/><Line dataKey="value" stroke={gold} strokeWidth={3}/></LineChart></ResponsiveContainer></GlassCard>}
export function AuditLogs(){return <DashboardLayout role="admin"><Header title="Audit Logs" subtitle="View logs, export logs, filter records, and inspect details."/><Toolbar><Button variant="outline"><Filter className="mr-2 h-4 w-4"/>Filter Logs</Button><Button><Download className="mr-2 h-4 w-4"/>Export Logs</Button></Toolbar><Table heads={["User","Action","Module","Date","Time"]} rows={[["Elena Rodriguez","Updated role permission","Roles","18/06/2026","10:40"],["Sarah Jenkins","Created job","Jobs","18/06/2026","09:12"]]} actions={()=><Action to="/admin/audit-logs/details">View Log</Action>}/></DashboardLayout>}
export function Notifications(){return <DashboardLayout role="admin"><Header title="Notifications" subtitle="Review and route platform notifications to related pages."/><div className="flex justify-end mb-4"><Button>Mark All Read</Button></div>{[["User Registered","User Kavishi registered.","/admin/users/profile"],["Organization Created","Acme Corp was created.","/admin/organizations/profile"],["Job Posted","Software Engineer Intern posted.","/admin/jobs/details"],["AI Alert","Resume parser accuracy changed.","/admin/ai-monitoring"]].map(([t,m,to])=><GlassCard key={t} className="p-5 mb-3 cursor-pointer hover:border-[#D4AF37]/40" onClick={()=>location.assign(to)}><div className="flex justify-between"><div><h2 className="text-white font-semibold">{t}</h2><p className="text-gray-400">{m}</p><p className="text-xs text-gray-500 mt-2">18/06/2026 • Unread</p></div><Button variant="outline">Mark as Read</Button></div></GlassCard>)}</DashboardLayout>}

export function AdminSettings(){return <DashboardLayout role="admin"><Header title="Settings" subtitle="General, security, email, AI, subscription plan, backup, and recovery configuration."/><Tabs defaultValue="general"><TabsList className="bg-[#1E1E1E] border border-[#D4AF37]/10 h-auto flex flex-wrap mb-5"><TabsTrigger value="general">General Settings</TabsTrigger><TabsTrigger value="security">Security Settings</TabsTrigger><TabsTrigger value="email">Email Configuration</TabsTrigger><TabsTrigger value="ai">AI Configuration</TabsTrigger><TabsTrigger value="plans">Subscription Plans</TabsTrigger><TabsTrigger value="backup">Backup & Recovery</TabsTrigger></TabsList>{["general","security","email","ai","plans","backup"].map(tab=><TabsContent key={tab} value={tab}><SettingsPanel tab={tab}/></TabsContent>)}</Tabs></DashboardLayout>}
function SettingsPanel({tab}:{tab:string}){const labels:Record<string,string[]>= {general:["Edit Settings","Save Changes"],security:["Change Security Rules","Enable MFA"],email:["Update SMTP","Test Email"],ai:["Update AI Settings"],plans:["Create Plan","Edit Plan","Delete Plan"],backup:["Create Backup","Restore Backup","Download Backup"]};return <GlassCard className="p-6"><h2 className="text-xl text-white font-semibold mb-4">{tab.replace(/^./,c=>c.toUpperCase())}</h2><div className="grid md:grid-cols-2 gap-4"><Input placeholder="Configuration name" className="bg-[#2D2D2D] border-[#D4AF37]/20 text-white"/><Input placeholder="Configuration value" className="bg-[#2D2D2D] border-[#D4AF37]/20 text-white"/></div><div className="mt-5 flex flex-wrap gap-3">{labels[tab].map((x,i)=><Button key={x} variant={i?"outline":"default"}>{x}</Button>)}</div></GlassCard>}
export function AdminProfile(){return <DashboardLayout role="admin"><Header title="My Profile" subtitle="Administrator profile, password, photo, and contact information."/><GlassCard className="p-6"><div className="flex gap-5 items-center"><Avatar className="h-20 w-20 border border-[#D4AF37]/40"><AvatarFallback className="bg-[#D4AF37]/10 text-[#D4AF37] text-2xl">ER</AvatarFallback></Avatar><div><h2 className="text-2xl text-white font-semibold">Elena Rodriguez</h2><p className="text-gray-400">elena@talentai.com • +1 555 0100</p><Badge className="mt-2 bg-[#D4AF37]/15 text-[#D4AF37]">Administrator Role</Badge></div></div><div className="mt-6 flex flex-wrap gap-3"><Button>Edit Profile</Button><Button variant="outline">Change Password</Button><Button variant="outline">Upload Photo</Button><Button variant="outline">Save Changes</Button></div></GlassCard></DashboardLayout>}

export function Detail({ title, items }: { title: string; items: string[] }) { return <DashboardLayout role="admin"><Header title={title} subtitle="Detailed administrator record view with related enterprise workflow data."/><div className="grid md:grid-cols-2 gap-5">{items.map(i=><GlassCard key={i} className="p-6 cursor-pointer hover:border-[#D4AF37]/40"><h2 className="text-xl text-white font-semibold">{i}</h2><p className="text-gray-400 mt-2">Complete {i.toLowerCase()} displayed here with activity and audit metadata.</p></GlassCard>)}</div></DashboardLayout>}
export function FormPage({ title, fields }: { title: string; fields: string[] }) { return <DashboardLayout role="admin"><Header title={title} subtitle="Enterprise form with validation, save actions, and audit logging."/><GlassCard className="p-6"><div className="grid md:grid-cols-2 gap-4">{fields.map(f=><Input key={f} placeholder={f} className="bg-[#2D2D2D] border-[#D4AF37]/20 text-white"/>)}</div><div className="mt-5 flex gap-3"><Button>Save Changes</Button><Button variant="outline">Cancel</Button></div></GlassCard></DashboardLayout>}
