import { useState, type ReactNode } from "react";
import { DashboardLayout } from "../../components/DashboardLayout";
import { GlassCard } from "../../components/GlassCard";
import { StatCard } from "../../components/StatCard";
import { Button } from "../../components/ui/button";
import { Input } from "../../components/ui/input";
import { Badge } from "../../components/ui/badge";
import { Textarea } from "../../components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "../../components/ui/select";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "../../components/ui/tabs";
import { Avatar, AvatarFallback } from "../../components/ui/avatar";
import { Switch } from "../../components/ui/switch";
import { BarChart, Bar, LineChart, Line, PieChart, Pie, Cell, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer } from "recharts";
import { BarChart3, Bell, Briefcase, Building, Calendar, CheckCircle2, Download, Edit3, Eye, FileText, Filter, Mail, MessageSquare, Phone, Plus, RefreshCcw, Search, Send, Settings, Shield, Sparkles, Star, Trash2, UserPlus, Users, Video, XCircle } from "lucide-react";

const candidates = [
  { name: "Kavishi Rajasekara", job: "Software Engineer Intern", status: "Applied", score: 95, skills: "React, ASP.NET Core, SQL", email: "kavishi@email.com", phone: "+94 77 456 7890", edu: "BSc Software Engineering", exp: "Internship projects", rank: "🥇 #1" },
  { name: "Nimal Perera", job: "QA Intern", status: "Shortlisted", score: 89, skills: "Selenium, Java, API Testing", email: "nimal@email.com", phone: "+94 71 222 3344", edu: "HND IT", exp: "1 year QA", rank: "🥈 #2" },
  { name: "Kasun Silva", job: "Backend Developer", status: "Interview Scheduled", score: 84, skills: "Node, PostgreSQL, AWS", email: "kasun@email.com", phone: "+94 76 888 1010", edu: "BSc CS", exp: "2 years", rank: "🥉 #3" },
];
const jobs = ["Software Engineer Intern", "QA Intern", "Product Designer", "Backend Developer"];
const chartData = [{ name: "Applied", value: 420 }, { name: "Shortlisted", value: 126 }, { name: "Interviewed", value: 64 }, { name: "Hired", value: 18 }];

function Header({ title, subtitle }: { title: string; subtitle: string }) { return <div className="mb-6"><p className="text-sm text-[#D4AF37]">Recruiter / {title}</p><h1 className="mt-2 text-3xl font-semibold text-white">{title}</h1><p className="text-gray-400 max-w-3xl">{subtitle}</p></div>; }
function Toolbar({ children }: { children: ReactNode }) { return <GlassCard className="p-4 mb-6"><div className="flex flex-wrap gap-3 items-center">{children}</div></GlassCard>; }
function CandidateActions() { return <div className="flex flex-wrap gap-2"><Button size="sm" variant="outline"><Eye className="mr-2 h-4 w-4" />View Profile</Button><Button size="sm" variant="outline"><FileText className="mr-2 h-4 w-4" />View Resume</Button><Button size="sm"><Star className="mr-2 h-4 w-4" />Shortlist</Button><Button size="sm" variant="outline"><Calendar className="mr-2 h-4 w-4" />Schedule Interview</Button><Button size="sm" variant="outline"><Send className="mr-2 h-4 w-4" />Send Message</Button></div>; }
function DataTable({ children }: { children: ReactNode }) { return <GlassCard className="overflow-hidden"><div className="overflow-x-auto"><table className="w-full min-w-[840px] text-sm">{children}</table></div></GlassCard>; }
function Th({ children }: { children: ReactNode }) { return <th className="px-5 py-4 text-left text-xs uppercase tracking-[0.18em] text-gray-500 border-b border-[#D4AF37]/10">{children}</th>; }
function Td({ children }: { children: ReactNode }) { return <td className="px-5 py-4 border-b border-[#D4AF37]/10 text-gray-300 align-top">{children}</td>; }

export function RecruiterProfile() { return <DashboardLayout role="recruiter"><Header title="Recruiter Profile" subtitle="Your recruiter identity and communication preferences." /><GlassCard className="p-6"><div className="flex items-center gap-5"><Avatar className="h-20 w-20 border border-[#D4AF37]/40"><AvatarFallback className="bg-[#D4AF37]/10 text-[#D4AF37] text-2xl">SJ</AvatarFallback></Avatar><div><h2 className="text-2xl text-white font-semibold">Sarah Jenkins</h2><p className="text-gray-400">Senior Technical Recruiter • Acme Corp</p><p className="text-[#D4AF37] text-sm mt-1">sarah.jenkins@acme.com</p></div></div><div className="grid md:grid-cols-2 gap-4 mt-6"><Input defaultValue="Sarah Jenkins" className="bg-[#2D2D2D] border-[#D4AF37]/20 text-white" /><Input defaultValue="Senior Technical Recruiter" className="bg-[#2D2D2D] border-[#D4AF37]/20 text-white" /><Input defaultValue="sarah.jenkins@acme.com" className="bg-[#2D2D2D] border-[#D4AF37]/20 text-white" /><Input defaultValue="Acme Corp" className="bg-[#2D2D2D] border-[#D4AF37]/20 text-white" /></div><Button className="mt-5">Save Profile</Button></GlassCard></DashboardLayout>; }

export function RecruiterDashboard() { return <DashboardLayout role="recruiter"><Header title="Recruiter Dashboard" subtitle="Premium command center for hiring performance, candidate pipelines, interviews, and AI-assisted decisions." /><div className="grid md:grid-cols-2 xl:grid-cols-5 gap-4 mb-6"><StatCard title="Total Jobs Posted" value="42" icon={Briefcase}/><StatCard title="Applications" value="1,284" icon={FileText}/><StatCard title="Shortlisted" value="186" icon={Star}/><StatCard title="Interviews" value="64" icon={Calendar}/><StatCard title="Hired" value="18" icon={CheckCircle2}/></div><div className="grid xl:grid-cols-3 gap-6"><GlassCard className="xl:col-span-2 p-6"><h2 className="text-xl text-white font-semibold mb-4">Applications Overview</h2><ResponsiveContainer width="100%" height={300}><BarChart data={chartData}><CartesianGrid strokeDasharray="3 3" stroke="#2D2D2D"/><XAxis dataKey="name" stroke="#999"/><YAxis stroke="#999"/><Tooltip contentStyle={{backgroundColor:"#1E1E1E",border:"1px solid rgba(212,175,55,.25)",color:"#fff"}}/><Bar dataKey="value" fill="#D4AF37" radius={[8,8,0,0]}/></BarChart></ResponsiveContainer></GlassCard><GlassCard className="p-6"><h2 className="text-xl text-white font-semibold mb-4">Priority Pipeline</h2>{candidates.map(c=><div key={c.name} className="p-3 rounded-xl bg-[#2D2D2D]/50 border border-[#D4AF37]/10 mb-3"><div className="flex justify-between"><span className="text-white">{c.name}</span><Badge className="bg-[#D4AF37]/15 text-[#D4AF37]">{c.score}%</Badge></div><p className="text-xs text-gray-400 mt-1">{c.job} • {c.status}</p></div>)}</GlassCard></div></DashboardLayout>; }

export function JobPostings() { return <DashboardLayout role="recruiter"><Header title="Job Postings" subtitle="Create, update, close, reopen, and monitor job vacancies." /><GlassCard className="p-6 mb-6"><h2 className="text-xl text-white font-semibold mb-4">Create Job</h2><div className="grid md:grid-cols-2 gap-4"><Input placeholder="Job Title" className="bg-[#2D2D2D] border-[#D4AF37]/20 text-white"/><Input placeholder="Required Skills" className="bg-[#2D2D2D] border-[#D4AF37]/20 text-white"/><Select><SelectTrigger className="bg-[#2D2D2D] border-[#D4AF37]/20 text-white"><SelectValue placeholder="Employment Type"/></SelectTrigger><SelectContent><SelectItem value="full">Full-Time</SelectItem><SelectItem value="part">Part-Time</SelectItem><SelectItem value="intern">Internship</SelectItem></SelectContent></Select><Input placeholder="Location" className="bg-[#2D2D2D] border-[#D4AF37]/20 text-white"/><Input placeholder="Salary Range (Optional)" className="bg-[#2D2D2D] border-[#D4AF37]/20 text-white"/><Input type="date" className="bg-[#2D2D2D] border-[#D4AF37]/20 text-white"/><Select><SelectTrigger className="bg-[#2D2D2D] border-[#D4AF37]/20 text-white"><SelectValue placeholder="Job Status"/></SelectTrigger><SelectContent><SelectItem value="open">Open</SelectItem><SelectItem value="closed">Closed</SelectItem></SelectContent></Select><Textarea placeholder="Job Description" className="md:col-span-2 bg-[#2D2D2D] border-[#D4AF37]/20 text-white"/></div><Button className="mt-5"><Plus className="mr-2 h-4 w-4"/>Create Job</Button></GlassCard><DataTable><thead><tr><Th>Job Title</Th><Th>Location</Th><Th>Deadline</Th><Th>Status</Th><Th>Actions</Th></tr></thead><tbody>{jobs.map((j,i)=><tr key={j}><Td><b className="text-white">{j}</b><p className="text-xs text-gray-500">{i%2?'Full-Time':'Internship'}</p></Td><Td>Colombo / Hybrid</Td><Td>30/06/2026</Td><Td><Badge className={i===2?"bg-red-500/15 text-red-400":"bg-green-500/15 text-green-400"}>{i===2?'Closed':'Open'}</Badge></Td><Td><div className="flex gap-2 flex-wrap"><Button size="sm" variant="outline"><Edit3 className="h-4 w-4"/></Button><Button size="sm" variant="outline"><RefreshCcw className="h-4 w-4"/></Button><Button size="sm" variant="ghost" className="text-red-400"><Trash2 className="h-4 w-4"/></Button><Button size="sm">{i===2?'Reopen':'Close'} Job</Button></div></Td></tr>)}</tbody></DataTable></DashboardLayout>; }

export function CandidatesPage() { const [tab,setTab]=useState("all"); return <DashboardLayout role="recruiter"><Header title="Candidates" subtitle="Search, filter, export, and evaluate candidates with recruiter workflow actions." /><Toolbar><Input placeholder="Search Candidate" className="max-w-xs bg-[#2D2D2D] border-[#D4AF37]/20 text-white"/><Button variant="outline"><Filter className="mr-2 h-4 w-4"/>Filter Candidate</Button><Button><Download className="mr-2 h-4 w-4"/>Export Candidates</Button><Select><SelectTrigger className="w-44 bg-[#2D2D2D] border-[#D4AF37]/20 text-white"><SelectValue placeholder="Skills"/></SelectTrigger><SelectContent><SelectItem value="react">React</SelectItem><SelectItem value="qa">QA</SelectItem></SelectContent></Select><Select><SelectTrigger className="w-44 bg-[#2D2D2D] border-[#D4AF37]/20 text-white"><SelectValue placeholder="Experience"/></SelectTrigger><SelectContent><SelectItem value="0-1">0-1 year</SelectItem><SelectItem value="2+">2+ years</SelectItem></SelectContent></Select></Toolbar><Tabs value={tab} onValueChange={setTab}><TabsList className="bg-[#1E1E1E] border border-[#D4AF37]/10 mb-4"><TabsTrigger value="all">All Candidates</TabsTrigger><TabsTrigger value="shortlisted">Shortlisted Candidates</TabsTrigger><TabsTrigger value="interview">Interview Candidates</TabsTrigger><TabsTrigger value="selected">Selected Candidates</TabsTrigger></TabsList><TabsContent value={tab}><DataTable><thead><tr><Th>Candidate Name</Th><Th>Applied Job</Th><Th>Status</Th><Th>Actions</Th></tr></thead><tbody>{candidates.map(c=><tr key={c.name}><Td><div className="flex gap-3"><Avatar><AvatarFallback className="bg-[#D4AF37]/10 text-[#D4AF37]">{c.name.split(' ').map(n=>n[0]).join('')}</AvatarFallback></Avatar><div><b className="text-white">{c.name}</b><p className="text-xs text-gray-500">{c.email}</p></div></div></Td><Td>{c.job}</Td><Td><Badge variant="outline" className="border-[#D4AF37]/30 text-[#D4AF37]">{c.status}</Badge></Td><Td><CandidateActions/></Td></tr>)}</tbody></DataTable></TabsContent></Tabs></DashboardLayout>; }

export function ApplicationReview() { return <DashboardLayout role="recruiter"><Header title="Application Review" subtitle="Review submitted applications, AI resume scores, candidate profiles, and talent-pool decisions." />{candidates.map(c=><GlassCard key={c.name} className="p-6 mb-5"><div className="flex flex-col xl:flex-row justify-between gap-5"><div className="flex gap-4"><Avatar className="h-14 w-14"><AvatarFallback className="bg-[#D4AF37]/10 text-[#D4AF37]">{c.name.split(' ').map(n=>n[0]).join('')}</AvatarFallback></Avatar><div><h2 className="text-xl text-white font-semibold">{c.name}</h2><p className="text-gray-400">{c.email} • {c.phone}</p><p className="text-[#D4AF37] text-sm mt-1">Applied Position: {c.job} • Applied Date: 18/06/2026</p></div></div><Badge className="bg-[#D4AF37]/15 text-[#D4AF37] h-fit">Resume Score {c.score}%</Badge></div><div className="grid md:grid-cols-4 gap-3 mt-5 text-sm"><Info label="Professional Info" value={c.exp}/><Info label="Education" value={c.edu}/><Info label="Skills" value={c.skills}/><Info label="Portfolio / GitHub" value="github.com/candidate"/></div><div className="grid md:grid-cols-3 gap-3 mt-5"><Info label="Skill Match" value={`${c.score}%`}/><Info label="Recommended Status" value={c.score>90?'Shortlist':'Review Further'}/><Info label="Resume" value="Candidate_CV.pdf"/></div><div className="mt-5 flex flex-wrap gap-2"><Button><Star className="mr-2 h-4 w-4"/>Shortlist</Button><Button variant="outline"><Calendar className="mr-2 h-4 w-4"/>Schedule Interview</Button><Button variant="destructive"><XCircle className="mr-2 h-4 w-4"/>Reject</Button><Button variant="outline"><Eye className="mr-2 h-4 w-4"/>View Full Profile</Button><Button variant="outline"><FileText className="mr-2 h-4 w-4"/>View Resume</Button><Button variant="outline"><Download className="mr-2 h-4 w-4"/>Download Resume</Button><Button variant="outline"><Send className="mr-2 h-4 w-4"/>Send Message</Button><Button variant="outline"><UserPlus className="mr-2 h-4 w-4"/>Add To Talent Pool</Button></div></GlassCard>)}</DashboardLayout>; }
function Info({label,value}:{label:string;value:string}){return <div className="rounded-xl bg-[#2D2D2D]/50 border border-[#D4AF37]/10 p-3"><p className="text-xs text-gray-500 uppercase tracking-[.16em]">{label}</p><p className="text-white mt-1">{value}</p></div>}

export function AIRanking() { return <DashboardLayout role="recruiter"><Header title="AI Candidate Ranking" subtitle="Automatically rank applicants using transparent AI match, skills, experience, and education scoring."/><Toolbar><Input placeholder="Search Candidate" className="max-w-xs bg-[#2D2D2D] border-[#D4AF37]/20 text-white"/><Button variant="outline"><Filter className="mr-2 h-4 w-4"/>Filter by Job Position</Button><Button variant="outline"><BarChart3 className="mr-2 h-4 w-4"/>Sort by AI Score</Button><Button><Download className="mr-2 h-4 w-4"/>Export Report</Button></Toolbar><DataTable><thead><tr><Th>Rank</Th><Th>Candidate Name</Th><Th>Applied Position</Th><Th>AI Match Score</Th><Th>Skills</Th><Th>Experience</Th><Th>Education</Th><Th>Actions</Th></tr></thead><tbody>{candidates.map(c=><tr key={c.name}><Td><b className="text-[#D4AF37]">{c.rank}</b></Td><Td><b className="text-white">{c.name}</b></Td><Td>{c.job}</Td><Td><Badge className="bg-[#D4AF37]/15 text-[#D4AF37]">{c.score}%</Badge></Td><Td>{c.score}%</Td><Td>{c.score-6}%</Td><Td>{c.score-8}%</Td><Td><CandidateActions/></Td></tr>)}</tbody></DataTable></DashboardLayout>; }

export function InterviewsPage(){const interviews=["Scheduled","Pending","Completed","Cancelled","Rescheduled","No Show"];return <DashboardLayout role="recruiter"><Header title="Interviews" subtitle="Schedule online or onsite interviews, invitations, reminders, and AI evaluation summaries."/><Toolbar><Input placeholder="Search Candidate" className="max-w-xs bg-[#2D2D2D] border-[#D4AF37]/20 text-white"/><Input placeholder="Search Position" className="max-w-xs bg-[#2D2D2D] border-[#D4AF37]/20 text-white"/><Button variant="outline"><Filter className="mr-2 h-4 w-4"/>Filter by Status</Button><Button><Calendar className="mr-2 h-4 w-4"/>Schedule Interview</Button></Toolbar><div className="grid xl:grid-cols-2 gap-5">{candidates.slice(0,2).map((c,i)=><GlassCard key={c.name} className="p-6"><div className="flex justify-between"><div><h2 className="text-xl text-white font-semibold">INT-2026-{184+i}</h2><p className="text-gray-400">{c.name} • {c.job}</p></div><Badge className="bg-[#D4AF37]/15 text-[#D4AF37]">{interviews[i]}</Badge></div><div className="grid md:grid-cols-2 gap-3 mt-5"><Info label="Date" value="24/06/2026"/><Info label="Time" value="10:30 AM"/><Info label="Type" value={i?'Onsite Interview':'Online Interview'}/><Info label={i?'Location':'Meeting Platform'} value={i?'Building 4, Room 12':'Google Meet'}/><Info label="Meeting Link / Location" value={i?'Colombo HQ':'meet.google.com/talentai'}/><Info label="Created Date" value="18/06/2026"/></div><div className="mt-5 flex flex-wrap gap-2"><Button><Video className="mr-2 h-4 w-4"/>Join Meeting</Button><Button variant="outline">View Interview Details</Button><Button variant="outline"><Edit3 className="mr-2 h-4 w-4"/>Edit</Button><Button variant="outline"><RefreshCcw className="mr-2 h-4 w-4"/>Reschedule</Button><Button variant="destructive">Cancel</Button><Button variant="outline"><Send className="mr-2 h-4 w-4"/>Send Invitation</Button><Button variant="outline"><Bell className="mr-2 h-4 w-4"/>Send Reminder</Button></div><div className="mt-5 grid md:grid-cols-2 gap-3">{["AI Interview Evaluation","AI Candidate Performance Score","AI Interview Summary","Recommended Hiring Decision"].map(x=><div key={x} className="rounded-lg bg-[#D4AF37]/10 border border-[#D4AF37]/20 p-3 text-sm text-[#D4AF37]">🤖 {x}</div>)}</div></GlassCard>)}</div></DashboardLayout>}

export function TalentPool(){return <DashboardLayout role="recruiter"><Header title="Talent Pool" subtitle="Store promising candidates for future roles and invite them to apply."/><Toolbar><Input placeholder="Search" className="max-w-xs bg-[#2D2D2D] border-[#D4AF37]/20 text-white"/><Button variant="outline"><Filter className="mr-2 h-4 w-4"/>Filter</Button><Button><Download className="mr-2 h-4 w-4"/>Export List</Button><Select><SelectTrigger className="w-40 bg-[#2D2D2D] border-[#D4AF37]/20 text-white"><SelectValue placeholder="Skills"/></SelectTrigger><SelectContent><SelectItem value="react">React</SelectItem></SelectContent></Select></Toolbar><DataTable><thead><tr><Th>Candidate Name</Th><Th>Skills</Th><Th>Experience</Th><Th>Education</Th><Th>Status</Th><Th>Added Date</Th><Th>Actions</Th></tr></thead><tbody>{candidates.map(c=><tr key={c.name}><Td><b className="text-white">{c.name}</b><p className="text-xs text-gray-500">{c.email} • {c.phone}</p></Td><Td>{c.skills}</Td><Td>{c.exp}</Td><Td>{c.edu}</Td><Td><Badge variant="outline" className="text-[#D4AF37] border-[#D4AF37]/30">Future Fit</Badge></Td><Td>18/06/2026</Td><Td><div className="flex flex-wrap gap-2"><Button size="sm" variant="outline">View Profile</Button><Button size="sm" variant="outline">View Resume</Button><Button size="sm" variant="outline">Send Message</Button><Button size="sm">Invite To Apply</Button><Button size="sm" variant="ghost" className="text-red-400">Remove</Button></div></Td></tr>)}</tbody></DataTable></DashboardLayout>}

export function RecruiterAnalytics(){const sources=[{name:"LinkedIn",value:35,color:"#D4AF37"},{name:"Company Website",value:25,color:"#E5C158"},{name:"Referral",value:20,color:"#888"},{name:"Job Portal",value:20,color:"#555"}];return <DashboardLayout role="recruiter"><Header title="Analytics" subtitle="Hiring statistics, reports, funnel analytics, candidate sources, and job performance."/><Toolbar><Select><SelectTrigger className="w-44 bg-[#2D2D2D] border-[#D4AF37]/20 text-white"><SelectValue placeholder="Date Range"/></SelectTrigger><SelectContent><SelectItem value="weekly">Weekly</SelectItem><SelectItem value="monthly">Monthly</SelectItem><SelectItem value="yearly">Yearly</SelectItem></SelectContent></Select><Select><SelectTrigger className="w-56 bg-[#2D2D2D] border-[#D4AF37]/20 text-white"><SelectValue placeholder="Job Position"/></SelectTrigger><SelectContent>{jobs.map(j=><SelectItem key={j} value={j}>{j}</SelectItem>)}</SelectContent></Select><Button>View Reports</Button><Button variant="outline">Export PDF Report</Button><Button variant="outline">Export Excel Report</Button><Button variant="outline">Download Analytics</Button></Toolbar><div className="grid md:grid-cols-2 xl:grid-cols-5 gap-4 mb-6"><StatCard title="Total Jobs Posted" value="42" icon={Briefcase}/><StatCard title="Applications Received" value="1,284" icon={FileText}/><StatCard title="Shortlisted" value="186" icon={Star}/><StatCard title="Interviews Scheduled" value="64" icon={Calendar}/><StatCard title="Hired" value="18" icon={CheckCircle2}/></div><div className="grid xl:grid-cols-3 gap-6"><GlassCard className="p-6 xl:col-span-2"><h2 className="text-xl text-white font-semibold mb-4">Hiring Funnel</h2><ResponsiveContainer width="100%" height={300}><LineChart data={chartData}><CartesianGrid strokeDasharray="3 3" stroke="#2D2D2D"/><XAxis dataKey="name" stroke="#999"/><YAxis stroke="#999"/><Tooltip contentStyle={{backgroundColor:"#1E1E1E",border:"1px solid rgba(212,175,55,.25)",color:"#fff"}}/><Line type="monotone" dataKey="value" stroke="#D4AF37" strokeWidth={3}/></LineChart></ResponsiveContainer></GlassCard><GlassCard className="p-6"><h2 className="text-xl text-white font-semibold mb-4">Candidate Sources</h2><ResponsiveContainer width="100%" height={260}><PieChart><Pie data={sources} dataKey="value" outerRadius={90} label>{sources.map(s=><Cell key={s.name} fill={s.color}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer></GlassCard></div><GlassCard className="p-6 mt-6"><h2 className="text-xl text-white font-semibold mb-4">Job Performance</h2><div className="grid md:grid-cols-2 gap-4"><Info label="Most Applied Job" value="Software Engineer Intern — 420 applications"/><Info label="Least Applied Job" value="Product Designer — 32 applications"/></div></GlassCard></DashboardLayout>}

export function CompanySettings(){return <DashboardLayout role="recruiter"><Header title="Company Settings" subtitle="Company administration, recruiter management, workflow, billing, notification, and security settings."/><Tabs defaultValue="profile"><TabsList className="bg-[#1E1E1E] border border-[#D4AF37]/10 mb-5 flex flex-wrap h-auto"><TabsTrigger value="profile">Company Profile</TabsTrigger><TabsTrigger value="recruiters">Recruiters</TabsTrigger><TabsTrigger value="workflow">Workflow</TabsTrigger><TabsTrigger value="subscription">Subscription</TabsTrigger><TabsTrigger value="notifications">Notifications</TabsTrigger><TabsTrigger value="security">Security</TabsTrigger></TabsList><TabsContent value="profile"><SettingsCard title="Company Profile" fields={["Company Name","Industry","Company Website","Company Email","Phone Number","Company Address"]} area="Company Description" actions={["Edit Profile","Save Changes"]}/></TabsContent><TabsContent value="recruiters"><GlassCard className="p-6"><h2 className="text-xl text-white font-semibold mb-4">Recruiter Management</h2><DataTable><thead><tr><Th>Recruiter Name</Th><Th>Email</Th><Th>Role</Th><Th>Actions</Th></tr></thead><tbody>{["Sarah Jenkins","Mark Fernando"].map(n=><tr key={n}><Td>{n}</Td><Td>{n.toLowerCase().replace(' ','.')}@acme.com</Td><Td>Technical Recruiter</Td><Td><Button size="sm">Add Recruiter</Button><Button size="sm" variant="outline" className="ml-2">Edit</Button><Button size="sm" variant="ghost" className="ml-2 text-red-400">Remove</Button></Td></tr>)}</tbody></DataTable></GlassCard></TabsContent><TabsContent value="workflow"><SettingsCard title="Hiring Workflow" fields={["Default Application Statuses","Interview Stages","Auto Email Notifications"]} actions={["Edit Workflow","Save Changes"]}/></TabsContent><TabsContent value="subscription"><SettingsCard title="Subscription & Billing" fields={["Current Plan","Expiry Date","Payment History"]} actions={["Upgrade Plan","Renew Subscription"]}/></TabsContent><TabsContent value="notifications"><GlassCard className="p-6"><h2 className="text-xl text-white font-semibold mb-4">Notification Settings</h2>{["Application Alerts","Interview Notifications","Email Notifications"].map(x=><div key={x} className="flex justify-between py-3 border-b border-[#D4AF37]/10"><span className="text-gray-300">{x}</span><Switch defaultChecked/></div>)}<Button className="mt-5">Save Preferences</Button></GlassCard></TabsContent><TabsContent value="security"><SettingsCard title="Security Settings" fields={["Change Password","Two Factor Authentication","Login Activity"]} actions={["Change Password","Enable / Disable 2FA"]}/></TabsContent></Tabs></DashboardLayout>}
function SettingsCard({title,fields,area,actions}:{title:string;fields:string[];area?:string;actions:string[]}){return <GlassCard className="p-6"><h2 className="text-xl text-white font-semibold mb-5">{title}</h2><div className="grid md:grid-cols-2 gap-4">{fields.map(f=><Input key={f} placeholder={f} className="bg-[#2D2D2D] border-[#D4AF37]/20 text-white"/>)}{area&&<Textarea placeholder={area} className="md:col-span-2 bg-[#2D2D2D] border-[#D4AF37]/20 text-white"/>}</div><div className="mt-5 flex gap-3">{actions.map((a,i)=><Button key={a} variant={i?"default":"outline"}>{a}</Button>)}</div></GlassCard>}

export function RecruiterMessages(){return <DashboardLayout role="recruiter"><Header title="Messages" subtitle="Recruiter communication center for candidates and hiring teams."/><div className="grid xl:grid-cols-[360px_1fr] gap-6 h-[650px]"><GlassCard className="p-4"><Input placeholder="Search messages" className="bg-[#2D2D2D] border-[#D4AF37]/20 text-white mb-4"/>{candidates.map(c=><div key={c.name} className="p-3 rounded-xl bg-[#2D2D2D]/50 border border-[#D4AF37]/10 mb-2"><b className="text-white">{c.name}</b><p className="text-sm text-gray-400 truncate">Thanks for reviewing my application.</p></div>)}</GlassCard><GlassCard className="p-6 flex flex-col"><div className="flex justify-between border-b border-[#D4AF37]/10 pb-4"><div><h2 className="text-white font-semibold">Kavishi Rajasekara</h2><p className="text-[#D4AF37] text-sm">Software Engineer Intern</p></div><div className="flex gap-2"><Button variant="outline" size="icon"><Phone className="h-4 w-4"/></Button><Button variant="outline" size="icon"><Video className="h-4 w-4"/></Button></div></div><div className="flex-1 py-6"><p className="max-w-lg bg-[#2D2D2D] p-4 rounded-2xl text-gray-300">We reviewed your resume and would like to schedule an interview.</p></div><div className="flex gap-2"><Input placeholder="Type a message" className="bg-[#2D2D2D] border-[#D4AF37]/20 text-white"/><Button><Send className="h-4 w-4"/></Button></div></GlassCard></div></DashboardLayout>}
export function RecruiterNotifications(){return <DashboardLayout role="recruiter"><Header title="Notifications" subtitle="Application alerts, interview reminders, candidate updates, and system notifications."/>{["12 new applications received.","Kavishi Rajasekara accepted the interview invitation.","AI ranking report is ready for Software Engineer Intern.","Subscription renewal due in 14 days."].map((n,i)=><GlassCard key={n} className={`p-5 mb-3 ${i<2?'border-l-4 border-l-[#D4AF37]':''}`}><div className="flex justify-between"><p className="text-white">🔔 {n}</p><Badge>{i<2?'Unread':'Read'}</Badge></div><p className="text-xs text-gray-500 mt-2">18/06/2026 • 10:{40+i}</p></GlassCard>)}</DashboardLayout>}
