import { DashboardLayout } from "../../components/DashboardLayout";
import { GlassCard } from "../../components/GlassCard";
import { Button } from "../../components/ui/button";
import { Badge } from "../../components/ui/badge";
import { CheckCircle2, Clock, Lock, Pencil, Trash2 } from "lucide-react";

export function ApplicationTracking() {
  const apps = [
    { id: "APP-2026-1842", title: "Software Engineer Intern", company: "WSO2", location: "Colombo", type: "Internship", date: "18/06/2026", status: "Pending", editable: true, resume: "Kavishi_Rajasekara_CV.pdf", note: "Strong academic projects. Under recruiter review.", interview: "Pending" },
    { id: "APP-2026-1771", title: "Frontend Developer Intern", company: "99x", location: "Remote", type: "Internship", date: "12/06/2026", status: "Selected", editable: false, resume: "Kavishi_Rajasekara_CV.pdf", note: "Shortlisted for technical interview.", interview: "22/06/2026 10:30 AM" },
  ];
  const steps = ["Applied", "Under Review", "Shortlisted", "Interview Scheduled", "Offer Received"];
  return <DashboardLayout role="jobseeker"><div className="space-y-6"><div><p className="text-sm text-[#D4AF37]">Dashboard / Applications</p><h1 className="mt-2 text-3xl font-semibold text-white">Applications</h1><p className="text-gray-400">Track submitted applications, resume usage, recruiter notes, and recruitment progress.</p></div>{apps.map(app => <GlassCard key={app.id} className="p-6"><div className="flex flex-col xl:flex-row xl:items-start justify-between gap-5"><div><Badge className="mb-3 bg-[#D4AF37]/15 text-[#D4AF37] border-[#D4AF37]/30">{app.status}</Badge><h2 className="text-xl font-semibold text-white">{app.title}</h2><p className="text-gray-400">{app.company} • {app.location} • {app.type}</p><p className="text-sm text-gray-500 mt-2">Application ID: {app.id} • Applied Date: {app.date}</p></div><div className="flex flex-wrap gap-2">{app.editable ? <><Button variant="outline"><Pencil className="mr-2 h-4 w-4" />Edit Application</Button><Button variant="outline">Update Application</Button><Button variant="ghost" className="text-red-400"><Trash2 className="mr-2 h-4 w-4" />Withdraw Application</Button></> : <Button variant="outline" disabled><Lock className="mr-2 h-4 w-4" />Editing closed after deadline</Button>}</div></div><div className="mt-6 grid md:grid-cols-3 gap-4 text-sm"><Info label="Resume Used" value={app.resume} /><Info label="Resume Status" value="Active" /><Info label="Interview Date & Time" value={app.interview} /></div><div className="mt-6"><h3 className="text-white font-medium mb-3">Recruitment Progress</h3><div className="grid md:grid-cols-5 gap-3">{steps.map((s,i) => <div key={s} className="rounded-xl bg-[#2D2D2D]/50 border border-[#D4AF37]/10 p-3 text-sm text-gray-300 flex items-center gap-2">{i < (app.status === "Selected" ? 3 : 2) ? <CheckCircle2 className="h-4 w-4 text-green-400" /> : <Clock className="h-4 w-4 text-[#D4AF37]" />}{s}</div>)}</div></div><div className="mt-5 rounded-xl bg-[#2D2D2D]/45 border border-[#D4AF37]/10 p-4"><p className="text-gray-500 text-xs uppercase tracking-[0.18em]">Recruiter Notes</p><p className="text-gray-300 mt-1">{app.note}</p></div></GlassCard>)}</div></DashboardLayout>;
}
function Info({ label, value }: { label: string; value: string }) { return <div className="rounded-xl bg-[#2D2D2D]/45 border border-[#D4AF37]/10 p-4"><p className="text-gray-500 text-xs uppercase tracking-[0.18em]">{label}</p><p className="text-white mt-1">{value}</p></div>; }
