import { useNavigate } from "react-router";
import { DashboardLayout } from "../../components/DashboardLayout";
import { GlassCard } from "../../components/GlassCard";
import { Button } from "../../components/ui/button";
import { Input } from "../../components/ui/input";
import { Switch } from "../../components/ui/switch";
import { Avatar, AvatarFallback } from "../../components/ui/avatar";
import { Bell, Lock, Save, Shield, User } from "lucide-react";

export function SeekerSettings() {
  const navigate = useNavigate();
  return <DashboardLayout role="jobseeker"><div className="space-y-6"><div><p className="text-sm text-[#D4AF37]">Dashboard / Settings</p><h1 className="mt-2 text-3xl font-semibold text-white">Settings</h1><p className="text-gray-400">Account preferences for your Job Seeker workspace. Role switching is not available.</p></div><GlassCard className="p-6"><div className="flex flex-col md:flex-row md:items-center justify-between gap-5"><button onClick={() => navigate("/jobseeker/profile")} className="flex items-center gap-4 text-left"><Avatar className="h-16 w-16 border border-[#D4AF37]/40"><AvatarFallback className="bg-[#D4AF37]/10 text-[#D4AF37] text-xl">KR</AvatarFallback></Avatar><div><h2 className="text-xl font-semibold text-white">Kavishi Rajasekara</h2><p className="text-gray-400">Job Seeker • Software Engineering Undergraduate</p><p className="text-[#D4AF37] text-sm mt-1">Click avatar to open My Profile</p></div></button><div className="rounded-full border border-[#D4AF37]/20 bg-[#2D2D2D]/60 p-3"><Bell className="h-6 w-6 text-[#D4AF37]" /></div></div></GlassCard><div className="grid lg:grid-cols-2 gap-6"><GlassCard className="p-6"><h2 className="text-xl font-semibold text-white mb-5 flex gap-2"><User className="text-[#D4AF37]" />Account Settings</h2><div className="space-y-4"><Input className="bg-[#2D2D2D] border-[#D4AF37]/20 text-white" defaultValue="Kavishi Rajasekara" /><Input className="bg-[#2D2D2D] border-[#D4AF37]/20 text-white" defaultValue="kavishi.rajasekara@email.com" /><Input className="bg-[#2D2D2D] border-[#D4AF37]/20 text-white" defaultValue="Colombo, Sri Lanka" /></div><Button className="mt-5"><Save className="mr-2 h-4 w-4" />Save Changes</Button></GlassCard><GlassCard className="p-6"><h2 className="text-xl font-semibold text-white mb-5 flex gap-2"><Shield className="text-[#D4AF37]" />Notification & Security</h2><Setting label="Application status alerts" defaultOn /><Setting label="New AI job matches" defaultOn /><Setting label="Recruiter messages" defaultOn /><Setting label="Two-factor authentication" defaultOn /><Setting label="Weekly career digest" /></GlassCard></div><GlassCard className="p-6"><h2 className="text-xl font-semibold text-white mb-4 flex gap-2"><Lock className="text-[#D4AF37]" />Access Control</h2><p className="text-gray-300">This account is locked to the Job Seeker experience. Employer, Recruiter, Hiring Manager, and Administrator role switching controls are hidden and unavailable.</p></GlassCard></div></DashboardLayout>;
}
function Setting({ label, defaultOn }: { label: string; defaultOn?: boolean }) { return <div className="flex items-center justify-between border-b border-[#D4AF37]/10 py-3 last:border-0"><span className="text-gray-300">{label}</span><Switch defaultChecked={defaultOn} /></div>; }
